services:
  dcs-postgres:
    image: postgres:16.3-alpine
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 15432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  
  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - dcs-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 16543:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
