services:
  postgres:
    image: docker.io/postgres:16.3-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 15432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
