services:
  dcs-postgres:
    image: postgres:16.3-alpine
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - dcs-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: guttolaudie@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  default:
    name: postgres-network
    external: true
